services:
  api:
    build: .
    container_name: andeslink_api_container
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - andeslink_network

  evidently:
    image: python:3.11-slim
    container_name: andeslink_evidently_container
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - andeslink_network
    # Instalamos evidently e iniciamos la UI apuntando a la carpeta 'workspace'
    command: >
      sh -c "pip install evidently && 
             evidently ui --host 0.0.0.0 --port 8000 --workspace /app/workspace"
    depends_on:
      - api

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: andeslink_prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - andeslink_network

  grafana:
    image: grafana/grafana:10.2.0
    container_name: andeslink_grafana_container
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - andeslink_network
    depends_on:
      - prometheus

networks:
  andeslink_network:
    driver: bridge