scrape_configs:
  - job_name: "andeslink-api-metrics"
    metrics_path: "/metrics" 
    static_configs:
      # Cambia "api" por el nombre exacto que definiste en el container_name
      - targets: ["andeslink_api_container:8000"]