name: CI Proyecto AndesLink

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar DVC
      uses: iterative/setup-dvc@v1

    # Versión simplificada para DVC remoto
    - name: Configurar almacenamiento remoto de DVC
      run: |
        dvc remote modify origin url https://dagshub.com/JuanManuelResquin84/Portafolio_03_Proyecto_AndesLink_MLOps.dvc
        dvc remote modify origin --local auth basic
        dvc remote modify origin --local user ${{ secrets.DAGSHUB_USERNAME }}
        dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_churn_env2.txt
        pip install pytest

    - name: Descargar artefactos de DVC
      run: |
        dvc pull -r origin

    - name: Ejecutar pruebas con Pytest
      run: |
        pytest